### ISSUE TITLE
what went wrong

### ISSUE THREAD

**Issue by Adolph3671** [cumulo-autumn/StreamDiffusion#101]
(.venv) C:\StreamDiffusion-main>
(.venv) C:\StreamDiffusion-main>python -m streamdiffusion.tools.install-tensorrt
Traceback (most recent call last):
  File "C:\Users\Adolph\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Adolph\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\StreamDiffusion-main\.venv\lib\site-packages\streamdiffusion\tools\install-tensorrt.py", line 19, in <module>
    def install(cu: Optional[Literal["11", "12"]] = get_cuda_version_from_torch()):
  File "C:\StreamDiffusion-main\.venv\lib\site-packages\streamdiffusion\tools\install-tensorrt.py", line 16, in get_cuda_version_from_torch
    return torch.version.cuda.split(".")[0]
AttributeError: 'NoneType' object has no attribute 'split'(.venv) C:\StreamDiffusion-main>
(.venv) C:\StreamDiffusion-main>python -m streamdiffusion.tools.install-tensorrt
Traceback (most recent call last):
  File "C:\Users\Adolph\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Adolph\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\StreamDiffusion-main\.venv\lib\site-packages\streamdiffusion\tools\install-tensorrt.py", line 19, in <module>
    def install(cu: Optional[Literal["11", "12"]] = get_cuda_version_from_torch()):
  File "C:\StreamDiffusion-main\.venv\lib\site-packages\streamdiffusion\tools\install-tensorrt.py", line 16, in get_cuda_version_from_torch
    return torch.version.cuda.split(".")[0]
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by angelolanche** [comment]
I'm in the exactly same error 
did you find a solution?
