### ISSUE TITLE
No module named 'fire'

### ISSUE THREAD

**Issue by fromann** [cumulo-autumn/StreamDiffusion#104]
~~~cmd
(streamdiffusion) D:\Project\StreamDiffusion\StreamDiffusion>python -m streamdiffusion.tools.install-tensorrt
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Traceback (most recent call last):
  File "D:\Project\Conda\envs\streamdiffusion\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Project\Conda\envs\streamdiffusion\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Project\Conda\envs\streamdiffusion\lib\site-packages\streamdiffusion\tools\install-tensorrt.py", line 3, in <module>
    import fire
ModuleNotFoundError: No module named 'fire'

(streamdiffusion) D:\Project\StreamDiffusion\StreamDiffusion>pip3 install fire
Requirement already satisfied: fire in d:\project\conda\envs\streamdiffusion\lib\site-packages (0.5.0)
Requirement already satisfied: six in d:\project\conda\envs\streamdiffusion\lib\site-packages (from fire) (1.16.0)
Requirement already satisfied: termcolor in d:\project\conda\envs\streamdiffusion\lib\site-packages (from fire) (2.4.0)
’
(streamdiffusion) D:\Project\StreamDiffusion\StreamDiffusion
~~~

Errors that occur after the third step
Cuda version 12.3 installed cuda version 12.1
System environment: Windows 10
Python environment: Conda Python 3.10

Running this line of code, （`Errors that occur after the third step

Cuda version 12.3 installed cuda version 12.1

System environment: Windows 10

Python environment: Conda Python 3.10

Running this line of code, as well as other example codes, all report an error of no model`）as well as other example codes, all report an error of no model

可以使用中文回复

**Comment by fromann** [comment]
> ```batchfile
> (streamdiffusion) D:\Project\StreamDiffusion\StreamDiffusion>python -m streamdiffusion.tools.install-tensorrt
> A matching Triton is not available, some optimizations will not be enabled.
> Error caught was: No module named 'triton'
> Traceback (most recent call last):
>   File "D:\Project\Conda\envs\streamdiffusion\lib\runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "D:\Project\Conda\envs\streamdiffusion\lib\runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "D:\Project\Conda\envs\streamdiffusion\lib\site-packages\streamdiffusion\tools\install-tensorrt.py", line 3, in <module>
>     import fire
> ModuleNotFoundError: No module named 'fire'
> 
> (streamdiffusion) D:\Project\StreamDiffusion\StreamDiffusion>pip3 install fire
> Requirement already satisfied: fire in d:\project\conda\envs\streamdiffusion\lib\site-packages (0.5.0)
> Requirement already satisfied: six in d:\project\conda\envs\streamdiffusion\lib\site-packages (from fire) (1.16.0)
> Requirement already satisfied: termcolor in d:\project\conda\envs\streamdiffusion\lib\site-packages (from fire) (2.4.0)
> ’
> (streamdiffusion) D:\Project\StreamDiffusion\StreamDiffusion
> ```
> 
> Errors that occur after the third step Cuda version 12.3 installed cuda version 12.1 System environment: Windows 10 Python environment: Conda Python 3.10
> 
> Running this line of code, （`Errors that occur after the third step
> 
> Cuda version 12.3 installed cuda version 12.1
> 
> System environment: Windows 10
> 
> Python environment: Conda Python 3.10
> 
> Running this line of code, as well as other example codes, all report an error of no model`）as well as other example codes, all report an error of no model
> 
> 可以使用中文回复

https://github.com/google/python-fire.git  python setup.py install
