### ISSUE TITLE
RuntimeError: Directory './frontend/dist' does not exist

### ISSUE THREAD

**Issue by GENGHAIJIAN007** [cumulo-autumn/StreamDiffusion#110]
(streamdiffusion) C:\Users\ghj\StreamDiffusion\demo\realtime-txt2img\frontend>cd ..

(streamdiffusion) C:\Users\ghj\StreamDiffusion\demo\realtime-txt2img>python main.py
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
vae\diffusion_pytorch_model.safetensors not found
Loading pipeline components...:  86%|███████████████████████████████████████████████▏       | 6/7 [00:05<00:01,  1.38s/it]C:\Users\ghj\python\envs\streamdiffusion\lib\site-packages\transformers\models\clip\feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
Loading pipeline components...: 100%|███████████████████████████████████████████████████████| 7/7 [00:05<00:00,  1.18it/s]
C:\Users\ghj\python\envs\streamdiffusion\lib\site-packages\diffusers\loaders\lora.py:952: FutureWarning: `fuse_text_encoder_lora` is deprecated and will be removed in version 0.25. You are using an old version of LoRA backend. This will be deprecated in the next releases in favor of PEFT make sure to install the latest PEFT and transformers packages in the future.
  deprecate("fuse_text_encoder_lora", "0.25", LORA_DEPRECATION_MESSAGE)
Traceback (most recent call last):
  File "C:\Users\ghj\StreamDiffusion\demo\realtime-txt2img\main.py", line 158, in <module>
    Api(config).app,
  File "C:\Users\ghj\StreamDiffusion\demo\realtime-txt2img\main.py", line 90, in __init__
    self.app.mount("/", StaticFiles(directory="./frontend/dist", html=True), name="public")
  File "C:\Users\ghj\python\envs\streamdiffusion\lib\site-packages\starlette\staticfiles.py", line 59, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory './frontend/dist' does not exist
This problem occurred while executing the main.py file in the demo folder

**Comment by teftef6220** [comment]
Please set up your Node.js environment.
https://github.com/cumulo-autumn/StreamDiffusion/tree/main/examples#:~:text=the%20capture%20area.-,You%20need%20to%20install%20extra%20dependencies%20for%20this%20script%20as%20follows%3A,-pip%20install%20%2Dr
