### ISSUE TITLE
No matching distribution for onnxruntime and tensorrt

### ISSUE THREAD

**Issue by syltensylten** [cumulo-autumn/StreamDiffusion#142]
Hello. Ive been trying to get streamdiffusion to install. Conquered a few problems on the way but now i require help. I get this error when pasting the command to install streamdiffusion. 

Command: pip install git+https://github.com/cumulo-autumn/StreamDiffusion.git@main#egg=streamdiffusion[tensorrt]

ERROR: Could not find a version that satisfies the requirement onnxruntime==1.16.3; extra == "tensorrt" (from streamdiffusion[tensorrt]) (from versions: 1.17.0, 1.17.1, 1.17.3)
ERROR: No matching distribution found for onnxruntime==1.16.3; extra == "tensorrt"

I have tried using: pip install onnxruntime==1.16., but it tells me thats not avalible. 

Im on CUDA 11.8 

Thanks

**Comment by syltensylten** [comment]
I've come past this now. I had to use Python 3.10 instead of 3.13. 

But now im stuck on this next error. Everything seemed to work out just fine. 

(.venv) PS C:\Users\PC1> python -m streamdiffusion.tools.install-tensorrt
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Installing TensorRT requirements...
Traceback (most recent call last):
  File "C:\Users\PC1\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\PC1\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\PC1\.venv\lib\site-packages\streamdiffusion\tools\install-tensorrt.py", line 54, in <module>
    fire.Fire(install)
  File "C:\Users\PC1\.venv\lib\site-packages\fire\core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\PC1\.venv\lib\site-packages\fire\core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\PC1\.venv\lib\site-packages\fire\core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\PC1\.venv\lib\site-packages\streamdiffusion\tools\install-tensorrt.py", line 26, in install
    if version("tensorrt") < Version("9.0.0"):
TypeError: '<' not supported between instances of 'NoneType' and 'Version'
