### ISSUE TITLE
problem when installing tensorrt

### ISSUE THREAD

**Issue by ccarmatic** [cumulo-autumn/StreamDiffusion#157]
CUDA 12.1, Windows 11, freshly installed Python 3.10.14 environment, with nothing installed

I have followed Step2(`pip3 install torch==2.1.0 torchvision==0.16.0 xformers --index-url https://download.pytorch.org/whl/cu121`
) and Step3(`pip install git+https://github.com/cumulo-autumn/StreamDiffusion.git@main#egg=streamdiffusion[tensorrt]`) , with no errors

upon typing `python -m streamdiffusion.tools.install-tensorrt` , this is the result
```
C:\Users\fdasfasdfasd\Documents\webcam_diffusion>python -m streamdiffusion.tools.install-tensorrt
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Installing TensorRT requirements...
"C:\Users\fdasfasdfasd\AppData\Local\Programs\Python\Python310\python.exe" -m pip install nvidia-cudnn-cu12==8.9.4.25 --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting nvidia-cudnn-cu12==8.9.4.25
  Downloading nvidia_cudnn_cu12-8.9.4.25-py3-none-win_amd64.whl (734.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 734.8/734.8 MB 34.4 MB/s eta 0:00:00
Collecting nvidia-cublas-cu12
  Downloading nvidia_cublas_cu12-12.5.2.13-py3-none-win_amd64.whl (398.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 398.3/398.3 MB 36.4 MB/s eta 0:00:00
Collecting nvidia-cuda-nvrtc-cu12
  Downloading nvidia_cuda_nvrtc_cu12-12.5.40-py3-none-win_amd64.whl (38.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.7/38.7 MB 40.9 MB/s eta 0:00:00
Installing collected packages: nvidia-cuda-nvrtc-cu12, nvidia-cublas-cu12, nvidia-cudnn-cu12
Successfully installed nvidia-cublas-cu12-12.5.2.13 nvidia-cuda-nvrtc-cu12-12.5.40 nvidia-cudnn-cu12-8.9.4.25

[notice] A new release of pip is available: 23.0.1 -> 24.1
[notice] To update, run: python.exe -m pip install --upgrade pip
"C:\Users\fdasfasdfasd\AppData\Local\Programs\Python\Python310\python.exe" -m pip install --pre --extra-index-url https://pypi.nvidia.com tensorrt==9.0.1.post11.dev4 --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com, https://pypi.nvidia.com
Collecting tensorrt==9.0.1.post11.dev4
  Downloading https://pypi.nvidia.com/tensorrt/tensorrt-9.0.1.post11.dev4.tar.gz (18 kB)
  Preparing metadata (setup.py) ... done
Collecting tensorrt_libs==9.0.1.post11.dev4
  Downloading https://pypi.nvidia.com/tensorrt-libs/tensorrt_libs-9.0.1.post11.dev4-py2.py3-none-win_amd64.whl (1029.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 GB 34.5 MB/s eta 0:00:00
Collecting tensorrt_bindings==9.0.1.post11.dev4
  Downloading https://pypi.nvidia.com/tensorrt-bindings/tensorrt_bindings-9.0.1.post11.dev4-cp310-none-win_amd64.whl (708 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 708.4/708.4 kB ? eta 0:00:00
Collecting nvidia-cudnn-cu11
  Downloading https://developer.download.nvidia.com/compute/redist/nvidia-cudnn-cu11/nvidia-cudnn-cu11-2022.5.19.tar.gz (16 kB)
  Preparing metadata (setup.py) ... done
Collecting nvidia-cublas-cu11
  Downloading https://developer.download.nvidia.com/compute/redist/nvidia-cublas-cu11/nvidia-cublas-cu11-2022.4.8.tar.gz (16 kB)
  Preparing metadata (setup.py) ... done
Collecting nvidia-cuda-runtime-cu11
  Downloading https://developer.download.nvidia.com/compute/redist/nvidia-cuda-runtime-cu11/nvidia-cuda-runtime-cu11-2022.4.25.tar.gz (16 kB)
  Preparing metadata (setup.py) ... done
Collecting nvidia-cublas-cu117
  Downloading https://pypi.nvidia.com/nvidia-cublas-cu117/nvidia_cublas_cu117-11.10.1.25-py3-none-win_amd64.whl (315.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 315.0/315.0 MB 31.2 MB/s eta 0:00:00
Collecting nvidia-cuda-runtime-cu117
  Downloading https://pypi.nvidia.com/nvidia-cuda-runtime-cu117/nvidia_cuda_runtime_cu117-11.7.60-py3-none-win_amd64.whl (991 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 991.4/991.4 kB 61.3 MB/s eta 0:00:00
Collecting nvidia-cudnn-cu116
  Downloading nvidia-cudnn-cu116-0.0.1.dev5.tar.gz (4.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\fdasfasdfasd\AppData\Local\Temp\pip-install-fjtpuqh6\nvidia-cudnn-cu116_35570e7194e5414ea16ae203a0ee3e34\setup.py", line 152, in <module>
          raise RuntimeError(open("ERROR.txt", "r").read())
      RuntimeError:
      ###########################################################################################
      The package you are trying to install is only a placeholder project on PyPI.org repository.
      This package is hosted on NVIDIA Python Package Index.

      This package can be installed as:
      ```
      $ pip install nvidia-pyindex
      $ pip install nvidia-cudnn-cu116
      ```
      ###########################################################################################

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip is available: 23.0.1 -> 24.1
[notice] To update, run: python.exe -m pip install --upgrade pip
Error running command: -m pip install --pre --extra-index-url https://pypi.nvidia.com tensorrt==9.0.1.post11.dev4 --no-cache-dir
Traceback (most recent call last):
  File "C:\Users\fdasfasdfasd\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\fdasfasdfasd\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\fdasfasdfasd\AppData\Local\Programs\Python\Python310\lib\site-packages\streamdiffusion\tools\install-tensorrt.py", line 54, in <module>
    fire.Fire(install)
  File "C:\Users\fdasfasdfasd\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\fdasfasdfasd\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\fdasfasdfasd\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\fdasfasdfasd\AppData\Local\Programs\Python\Python310\lib\site-packages\streamdiffusion\tools\install-tensorrt.py", line 33, in install
    run_pip(
  File "C:\Users\fdasfasdfasd\AppData\Local\Programs\Python\Python310\lib\site-packages\streamdiffusion\pip_utils.py", line 52, in run_pip
    return run_python(f"-m pip {command}", env)
  File "C:\Users\fdasfasdfasd\AppData\Local\Programs\Python\Python310\lib\site-packages\streamdiffusion\pip_utils.py", line 46, in run_python
    raise RuntimeError(f"Error running command: {command}")
RuntimeError: Error running command: -m pip install --pre --extra-index-url https://pypi.nvidia.com tensorrt==9.0.1.post11.dev4 --no-cache-dir
```

**Comment by ccarmatic** [comment]
if I reinstall Python fresh, then do `pip3 install torch==2.1.0 torchvision==0.16.0 xformers --index-url https://download.pytorch.org/whl/cu118` to install PyTorch for CUDA 11.8 , it will not try to install cuddn116, and the installation passes... 

However, trying to actually launch Streamdiffusion will give `The procedure entry point?destroyTensorDescriptorEx@[ops@cudnn](mailto:ops@cudnn).... could not be located in the dynamic link library C:\Users\Admin\stable-diffusion-webui\venv\Lib\site-packages\nvidia\cudnn\bin\cudnn_adv_infer64_8.dll.`

**Comment by ccarmatic** [comment]
I can get past the nvidia-cudnn-cu116 install by manually installing cudnn: `pip install nvidia-cudnn-cu11==8.9.4.25` , this is also the version number of nvidia-cudnn-cu12 that  `streamdiffusion.tools.install-tensorrt` will install 

but then I get an error about the entry point: 
![image](https://github.com/cumulo-autumn/StreamDiffusion/assets/67438380/2b483d33-4dd7-4078-bd39-7e15a7f4deae)
