### ISSUE TITLE
tensorrt_bindings==9.0.1.post11.dev4 returning a non-zero exit status 1

### ISSUE THREAD

**Issue by potesd** [cumulo-autumn/StreamDiffusion#160]
`Collecting nvidia-cudnn-cu116 (from nvidia-cudnn-cu11->tensorrt_libs==9.0.1.post11.dev4)
        Downloading nvidia-cudnn-cu116-0.0.1.dev5.tar.gz (4.4 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'error'
        error: subprocess-exited-with-error

        Getting requirements to build wheel did not run successfully.
        exit code: 1

        [28 lines of output]
        Traceback (most recent call last):
          File "C:\Users\SNS\AI_RnD\StreamDiffusion\.venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
            main()
          File "C:\Users\SNS\AI_RnD\StreamDiffusion\.venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "C:\Users\SNS\AI_RnD\StreamDiffusion\.venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
            return hook(config_settings)
          File "C:\Users\SNS\AppData\Local\Temp\pip-build-env-fbot3og4\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
            return self._get_build_requires(config_settings, requirements=[])
          File "C:\Users\SNS\AppData\Local\Temp\pip-build-env-fbot3og4\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
            self.run_setup()
          File "C:\Users\SNS\AppData\Local\Temp\pip-build-env-fbot3og4\overlay\Lib\site-packages\setuptools\build_meta.py", line 497, in run_setup
            super().run_setup(setup_script=setup_script)
          File "C:\Users\SNS\AppData\Local\Temp\pip-build-env-fbot3og4\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
            exec(code, locals())
          File "<string>", line 152, in <module>
        RuntimeError:
        ###########################################################################################
        The package you are trying to install is only a placeholder project on PyPI.org repository.
        This package is hosted on NVIDIA Python Package Index.

        This package can be installed as:
        ```
        $ pip install nvidia-pyindex
        $ pip install nvidia-cudnn-cu116
        ```
        ###########################################################################################

        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error

      Getting requirements to build wheel did not run successfully.
      exit code: 1

      See above for output.`
      
     No matter what i do, when installing any version of StreamDiffusion TensorRT I get a non zero exit status 1. 
     
     This is a brand new issue and I think it's due to some hard coded URL or a defunct link of some kind. 
     
     When I then try to install the packages via the recommended commands 
     
     ` $ pip install nvidia-pyindex
        $ pip install nvidia-cudnn-cu116`
        
        both fail to build wheels too.

**Comment by ccarmatic** [comment]
I had this problem before, Nvidia's Python Package Index is kinda funky

for me, I had to manually install nvidia-cudnn-cu11==8.9.4.25 (the version that Streamdiffusion uses) , before I run the Streamdiffusion's TensorRT installation script ... it will detect the presence of CuDNN and skip trying to install cu116 , and proceed to install the rest of the components such as polygraphy and pywin32
