### ISSUE TITLE
screen/main.py  Cannot re-initialize CUDA in forked subprocess.

### ISSUE THREAD

**Issue by yhyu13** [cumulo-autumn/StreamDiffusion#17]
ubutn 22.04 Cuda12.1 RTX3090

when running

```
cd example
python screen/main.py
```

And then press enter to start the subprocess, I am havving cuda cannot run on forked subprocess error

```
(streamdiffusion) hangyu5@yhyu13fuwuqi:~/Documents/Git-repoMy/AIResearchVault/repo/AIGC/game changer/StreamDiffusion/examples$ python screen/main.py
vae/diffusion_pytorch_model.safetensors not found
Loading pipeline components...:  14%|███████████████████▋                                                                                                                      | 1/7 [00:01<00:09,  1.59s/it]/home/hangyu5/anaconda3/envs/streamdiffusion/lib/python3.11/site-packages/transformers-4.36.2-py3.11.egg/transformers/models/clip/feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.97it/s]
Traceback (most recent call last):
  File "/home/hangyu5/Documents/Git-repoMy/AIResearchVault/repo/AIGC/game changer/StreamDiffusion/examples/screen/../../utils/wrapper.py", line 413, in _load_model
    ).to(device=self.device, dtype=self.dtype)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hangyu5/anaconda3/envs/streamdiffusion/lib/python3.11/site-packages/diffusers-0.24.0-py3.11.egg/diffusers/pipelines/pipeline_utils.py", line 864, in to
    module.to(device, dtype)
  File "/home/hangyu5/anaconda3/envs/streamdiffusion/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/hangyu5/anaconda3/envs/streamdiffusion/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/hangyu5/anaconda3/envs/streamdiffusion/lib/python3.11/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/home/hangyu5/anaconda3/envs/streamdiffusion/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hangyu5/anaconda3/envs/streamdiffusion/lib/python3.11/site-packages/torch/cuda/__init__.py", line 284, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
Model load has failed. Doesn't exist.
```

**Comment by MoonEese** [comment]
https://github.com/cumulo-autumn/StreamDiffusion/tree/main/examples
Take a screen capture and process it. **This script only works on Windows.**

**Comment by yhyu13** [comment]
Ok! Thanks!
