### ISSUE TITLE
SDXL support

### ISSUE THREAD

**Issue by solitaryTian** [cumulo-autumn/StreamDiffusion#20]
Is this method support SDXL? I just replace the model with sdxl base. And it raise error

Traceback (most recent call last):
  File "/dfs/comicai/songtao.tian/StreamDiffusion/streamdiffusion_test.py", line 42, in <module>
    stream(init_image)
  File "/root/miniconda3/envs/streamdiffusion/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/dfs/comicai/songtao.tian/StreamDiffusion/src/streamdiffusion/pipeline.py", line 461, in __call__
    x_0_pred_out = self.predict_x0_batch(x_t_latent)
  File "/dfs/comicai/songtao.tian/StreamDiffusion/src/streamdiffusion/pipeline.py", line 399, in predict_x0_batch
    x_0_pred_batch, model_pred = self.unet_step(x_t_latent, t_list)
  File "/dfs/comicai/songtao.tian/StreamDiffusion/src/streamdiffusion/pipeline.py", line 313, in unet_step
    model_pred = self.unet(
  File "/root/miniconda3/envs/streamdiffusion/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/streamdiffusion/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/streamdiffusion/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 967, in forward
    if "text_embeds" not in added_cond_kwargs:
TypeError: argument of type 'NoneType' is not iterable

**Comment by teftef6220** [comment]
Thanks for the comment.

We do not currently support SD_XL.

The development team will look into supporting SD_XL.

**Comment by jayavanth** [comment]
@teftef6220 can you tell us what changes are needed? Maybe we can help

**Comment by teftef6220** [comment]
To achieve higher speeds, we need to develop an SDXL-compatible TensorRT and model architecture must be modified.
This will require significant changes to the pipeline, which could take a long time.

**Comment by hkn-g** [comment]
https://github.com/cumulo-autumn/StreamDiffusion/issues/114#issuecomment-2010267704

**Comment by hkn-g** [comment]
I have added SDXL support to the pipeline and wrapper based on @ApolloRay 's code (thanks for that!) (https://github.com/cumulo-autumn/StreamDiffusion/issues/114#issuecomment-1953697528). I have also added single image and real-time image generation examples for sdxl-turbo. Check out my sdxl branch.

https://github.com/hkn-g/StreamDiffusion/tree/sdxl

sdxl-turbo img2img looks fine, but there are some other issues, such as TensorRT not working, and text2img giving an error with an SDXL model. However, in img2img mode, it works without an input image.

**Comment by tebjan** [comment]
@hkn-g I got the same error as @solitaryTian. Do you happen to know what the issue could be? I am on the `sdxl` branch Windows 11 with Cuda 12.1 and I have created the venv as described in the readme of this repo:
https://github.com/hkn-g/StreamDiffusion/tree/sdxl

**Comment by hkn-g** [comment]
@tebjan With Cuda 12.1 I couldn't get a proper working setup, I got different errors each time. Then I installed Cuda 11.8 to get a fully working environment, that might be the problem. 
If only the SDXL model in txt2img mode gives this error, I haven't looked at that part in detail yet.

**Comment by tebjan** [comment]
> With Cuda 12.1 I couldn't get a proper working setup, I got different errors each time.

What errors did you get? With the fix that I PRed to your branch, your example for img2img works on my machine with win11, cuda 12.1, and a venv.

**Comment by hkn-g** [comment]
> What errors did you get?

I don't remember exactly, but I usually got dependency related errors related to xformers or TensorRT, but I think that was one of the errors somewhere. :)

By the way your commit (https://github.com/tebjan/StreamDiffusion/commit/a649ca55ea517d007e1f832a21b2830bf18da219) also fixed the txt2img issue in sdxl-turbo, thanks. I also updated the txt2img example for sdxl.

**Comment by chuck-ma** [comment]
It seems that sdxl (such as RunDiffusion/Juggernaut-XL-v9) doesn't work, but sdxl turbo works well.

**Comment by mflux** [comment]
I got it working by replacing wrapper.py StableDiffusionPipeline references with StableDiffusionXLPipeline. I reckon that ought to be an option to be passed to wrapper.

**Comment by hkn-g** [comment]
Hi @mflux  Are you sure it works on the [sdxl branch](https://github.com/hkn-g/StreamDiffusion/tree/sdxl) ? Because wrapper.py already automatically decides the pipeline (StableDiffusionXLPipeline or not) by checking the model name, or you can manually pass the sdxl=True parameter to the wrapper.

**Comment by deanvilgel** [comment]
Hello, i'm currently working on your branch  @hkn-g,  when using tensorrt acceleration, it seems to give none type iterable error. is tensorrt not available currently?

**Comment by thewhatifproject** [comment]
> Hello, i'm currently working on your branch [@hkn-g](https://github.com/hkn-g), when using tensorrt acceleration, it seems to give none type iterable error. is tensorrt not available currently?

Me too interested, nobody had a tensor sdxl turbo working setup?

`Exporting model: engines/sdxl-turbo--lcm_lora-False--tiny_vae-True--max_batch-2--min_batch-2--mode-img2img/unet.engine.onnx
Traceback (most recent call last):
  File "/workspace/webdiff/backend/utils/wrapper.py", line 572, in _load_model
    compile_unet(
  File "/root/miniconda3/envs/streamdiffsdxl/lib/python3.10/site-packages/streamdiffusion/acceleration/tensorrt/__init__.py", line 76, in compile_unet
    builder.build(
  File "/root/miniconda3/envs/streamdiffsdxl/lib/python3.10/site-packages/streamdiffusion/acceleration/tensorrt/builder.py", line 54, in build
    export_onnx(
  File "/root/miniconda3/envs/streamdiffsdxl/lib/python3.10/site-packages/streamdiffusion/acceleration/tensorrt/utilities.py", line 416, in export_onnx
    torch.onnx.export(
  File "/root/miniconda3/envs/streamdiffsdxl/lib/python3.10/site-packages/torch/onnx/utils.py", line 516, in export
    _export(
  File "/root/miniconda3/envs/streamdiffsdxl/lib/python3.10/site-packages/torch/onnx/utils.py", line 1596, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/root/miniconda3/envs/streamdiffsdxl/lib/python3.10/site-packages/torch/onnx/utils.py", line 1135, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/root/miniconda3/envs/streamdiffsdxl/lib/python3.10/site-packages/torch/onnx/utils.py", line 1011, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/root/miniconda3/envs/streamdiffsdxl/lib/python3.10/site-packages/torch/onnx/utils.py", line 915, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/root/miniconda3/envs/streamdiffsdxl/lib/python3.10/site-packages/torch/jit/_trace.py", line 1285, in _get_trace_graph
    outs = ONNXTracedModule(
  File "/root/miniconda3/envs/streamdiffsdxl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/streamdiffsdxl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/streamdiffsdxl/lib/python3.10/site-packages/torch/jit/_trace.py", line 133, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/root/miniconda3/envs/streamdiffsdxl/lib/python3.10/site-packages/torch/jit/_trace.py", line 124, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/root/miniconda3/envs/streamdiffsdxl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/streamdiffsdxl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/streamdiffsdxl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1508, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/envs/streamdiffsdxl/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 967, in forward
    if "text_embeds" not in added_cond_kwargs:
TypeError: argument of type 'NoneType' is not iterable`
