### ISSUE TITLE
when i execute "python vid2vid/main.py ", something wrong happend

### ISSUE THREAD

**Issue by wangbochao1** [cumulo-autumn/StreamDiffusion#31]
Traceback (most recent call last):
  File "/root/autodl-tmp/project/StreamDiffusion/examples/vid2vid/main.py", line 106, in <module>
    fire.Fire(main)
  File "/root/miniconda3/envs/streamdiffusion/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/streamdiffusion/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/streamdiffusion/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/autodl-tmp/project/StreamDiffusion/examples/vid2vid/main.py", line 99, in main
    video_result[i] = output_image.permute(1, 2, 0)
RuntimeError: The expanded size of the tensor (364) must match the existing size (600) at non-singleton dimension 1.  Target sizes: [604, 364, 3].  Tensor sizes: [360, 600, 3]

**Comment by earthwormjeff** [comment]
replace line 99 : 
        video_result[i] = output_image.permute(1, 2, 0)
with:
        video_result[i] = torch.permute(output_image, (2, 1, 0))

**Comment by wangbochao1** [comment]
thanks
