### ISSUE TITLE
Model load has failed.（txt2img or screen ）have the same error

### ISSUE THREAD

**Issue by whpwwy** [cumulo-autumn/StreamDiffusion#59]
windows11 
error infomation :

Traceback (most recent call last):
  File "E:\Study\AI\StreamDiffusion-main\examples\txt2img\..\..\utils\wrapper.py", line 411, in _load_model
    pipe: StableDiffusionPipeline = StableDiffusionPipeline.from_pretrained(
  File "C:\Users\whpww\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1090, in from_pretrained
    cached_folder = cls.download(
  File "C:\Users\whpww\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1649, in download
    info = model_info(
  File "C:\Users\whpww\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\whpww\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\hf_api.py", line 2084, in model_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)
  File "C:\Users\whpww\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\whpww\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\whpww\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\whpww\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\utils\_http.py", line 67, in send
    return super().send(request, *args, **kwargs)
  File "C:\Users\whpww\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/KBlueLeaf/kohaku-v2.1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000016FB6333C10>, 'Connection to huggingface.co timed out. (connect timeout=None)'))"), '(Request ID: c900e75e-2897-4ed0-94d4-2db8fec92845)')
**Model load has failed. Doesn't exist.**

**Comment by albireophyhe** [comment]
In your error message, it says `Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000016FB6333C10>, 'Connection to huggingface.co timed out. (connect timeout=None)'))"`, so firstly it looks like a problem from your environment. Try to download the model manually from huggingface and then load it from a specified local path :)

**Comment by whpwwy** [comment]
I download “kohaku-v2.1.safetensors” from huggingface.co
but i put it in ".\StreamDiffusion-main\models\Model", it is still error
could you tell me "the specified local path"

**Comment by whpwwy** [comment]
thanks, i fixed error

**Comment by willww64** [comment]
> @whpwwy can you share the method you used to fix the bug ? I meet the same error. and when i explict set model_id_or_path value as the model's folder. the model i downloaded mannual as : kohaku-v2.1.safetensors I got an error: OSError: Error no file named model_index.json found in directory /home/ltb/data/StreamDiffusion/models/KBlueLeaf/. Model load has failed. Doesn't exist.

Bro, you are in China. Please make it a habit to check your GFW proxy when encountering any network issues.  To all Chinese users, this issue may be caused by a broken proxy or misconfigured proxy rules.
