### ISSUE TITLE
what node.js and npm version?

### ISSUE THREAD

**Issue by siyehua** [cumulo-autumn/StreamDiffusion#71]
when I use the demo: npm run build, it report an error:
`
SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/data/home-siyehua/StreamDiffusion/demo/realtime-txt2img/view/node_modules/eslint-webpack-plugin/dist/getESLint.js:9:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! view@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the view@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/home-siyehua/.npm/_logs/2023-12-28T12_50_45_666Z-debug.log
`

and the log show:

`
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.11
3 info using node@v10.24.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle view@0.1.0~prebuild: view@0.1.0
6 info lifecycle view@0.1.0~build: view@0.1.0
7 verbose lifecycle view@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle view@0.1.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/data/home-siyehua/StreamDiffusion/demo/realtime-txt2img/view/node_modules/.bin:/data/home-siyehua/miniconda3/envs/streamdiffusion/bin:/data/home-siyehua/miniconda3/condabin:/data/home-siyehua/.local/bin:/data/home-siyehua/bin:/usr/local/cuda/bin:/usr/share/Modules/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/data/home-siyehua/.ft
9 verbose lifecycle view@0.1.0~build: CWD: /data/home-siyehua/StreamDiffusion/demo/realtime-txt2img/view
10 silly lifecycle view@0.1.0~build: Args: [ '-c', 'react-scripts build' ]
11 silly lifecycle view@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle view@0.1.0~build: Failed to exec build script
13 verbose stack Error: view@0.1.0 build: `react-scripts build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid view@0.1.0
15 verbose cwd /data/home-siyehua/StreamDiffusion/demo/realtime-txt2img/view
16 verbose Linux 5.4.119-19.0009.28
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v10.24.0
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 1
22 error view@0.1.0 build: `react-scripts build`
22 error Exit status 1
23 error Failed at the view@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

and my  node is v10.24.0, npm  v6.14.11,but react-scripts build error

**Comment by teftef6220** [comment]
Did you run npm install?

Node.js is fine with the latest version.

**Comment by nicholasVANDAL** [comment]
wow your node is so old.
their specs as v18, and it works fine with v20 (lts)
