### ISSUE TITLE
json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by korzen** [cumulo-autumn/StreamDiffusion#85]
Hi, I am getting the following error on Windows when launching examples

`(streamdiffusion) PS E:\StreamDiffusion\examples> python txt2img/single.py --output output.png --prompt "A cat with a hat"
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
unet\diffusion_pytorch_model.safetensors not found
Loading pipeline components...:  29%|████████████████████████████████████████████████████████████▌                                                                                                                                                       | 2/7 [00:04<00:10,  2.05s/it]E:\Anaconda\envs\streamdiffusion\lib\site-packages\transformers\models\clip\feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:05<00:00,  1.22it/s]
E:\Anaconda\envs\streamdiffusion\lib\site-packages\diffusers\loaders\lora.py:952: FutureWarning: `fuse_text_encoder_lora` is deprecated and will be removed in version 0.25. You are using an old version of LoRA backend. This will be deprecated in the next releases in favor of PEFT make sure to install the latest PEFT and transformers packages in the future.
  deprecate("fuse_text_encoder_lora", "0.25", LORA_DEPRECATION_MESSAGE)
Traceback (most recent call last):
  File "E:\Anaconda\envs\streamdiffusion\lib\site-packages\diffusers\configuration_utils.py", line 424, in load_config
    config_dict = cls._dict_from_json_file(config_file)
  File "E:\Anaconda\envs\streamdiffusion\lib\site-packages\diffusers\configuration_utils.py", line 547, in _dict_from_json_file
    return json.loads(text)
  File "E:\Anaconda\envs\streamdiffusion\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "E:\Anaconda\envs\streamdiffusion\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "E:\Anaconda\envs\streamdiffusion\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\StreamDiffusion\examples\txt2img\single.py", line 82, in <module>
    fire.Fire(main)
  File "E:\Anaconda\envs\streamdiffusion\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "E:\Anaconda\envs\streamdiffusion\lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "E:\Anaconda\envs\streamdiffusion\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "E:\StreamDiffusion\examples\txt2img\single.py", line 54, in main
    stream = StreamDiffusionWrapper(
  File "E:\StreamDiffusion\examples\txt2img\..\..\utils\wrapper.py", line 152, in __init__
    self.stream: StreamDiffusion = self._load_model(
  File "E:\StreamDiffusion\examples\txt2img\..\..\utils\wrapper.py", line 463, in _load_model
    stream.vae = AutoencoderTiny.from_pretrained("madebyollin/taesd").to(
  File "E:\Anaconda\envs\streamdiffusion\lib\site-packages\diffusers\models\modeling_utils.py", line 712, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
  File "E:\Anaconda\envs\streamdiffusion\lib\site-packages\diffusers\configuration_utils.py", line 428, in load_config
    raise EnvironmentError(f"It looks like the config file at '{config_file}' is not a valid JSON file.")
OSError: It looks like the config file at 'C:\Users\korze\.cache\huggingface\hub\models--madebyollin--taesd\snapshots\b7456fca7c8110c3aaadf5edf34b05bfb2a1af55\config.json' is not a valid JSON file.
(streamdiffusion) PS E:\StreamDiffusion\examples>`

**Comment by korzen** [comment]
OK I cleared the hub's cache and not it is working (C:\Users\korze\.cache\huggingface\hub)
