### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by YuanBo66668888** [cumulo-autumn/StreamDiffusion#90]
```
/root/anaconda3/envs/streamsd/lib/python3.10/site-packages/diffusers/loaders/lora.py:952: FutureWarning: `fuse_text_encoder_lora` is deprecated and will be removed in version 0.25. You are using an old version of LoRA backend. This will be deprecated in the next releases in favor of PEFT make sure to install the latest PEFT and transformers packages in the future.
  deprecate("fuse_text_encoder_lora", "0.25", LORA_DEPRECATION_MESSAGE)
Traceback (most recent call last):
  File "/home/StreamDiffusion/examples/txt2img/single.py", line 83, in <module>
    fire.Fire(main)
  File "/root/anaconda3/envs/streamsd/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/anaconda3/envs/streamsd/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/anaconda3/envs/streamsd/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/StreamDiffusion/examples/txt2img/single.py", line 78, in main
    output_image = stream()
  File "/home/StreamDiffusion/examples/txt2img/../../utils/wrapper.py", line 230, in __call__
    return self.txt2img(prompt)
  File "/home/StreamDiffusion/examples/txt2img/../../utils/wrapper.py", line 254, in txt2img
    image_tensor = self.stream.txt2img(self.frame_buffer_size)
  File "/root/anaconda3/envs/streamsd/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/streamsd/lib/python3.10/site-packages/streamdiffusion/pipeline.py", line 473, in txt2img
    x_0_pred_out = self.predict_x0_batch(
  File "/root/anaconda3/envs/streamsd/lib/python3.10/site-packages/streamdiffusion/pipeline.py", line 423, in predict_x0_batch
    x_0_pred, model_pred = self.unet_step(x_t_latent, t, idx)
  File "/root/anaconda3/envs/streamsd/lib/python3.10/site-packages/streamdiffusion/pipeline.py", line 313, in unet_step
    model_pred = self.unet(
  File "/root/anaconda3/envs/streamsd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/streamsd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/streamsd/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 1035, in forward
    sample = self.conv_in(sample)
  File "/root/anaconda3/envs/streamsd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/streamsd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/streamsd/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/root/anaconda3/envs/streamsd/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: GET was unable to find an engine to execute this computation
(streamsd) [root@iZ8vbe58az41quqd311x5rZ txt2img]# 
```
env:
cuda:11.8
python 3.10
torch: 2.1.0
torchvision: 0.16.0

**Comment by YuanBo66668888** [comment]
I solved.

**Comment by jasperan** [comment]
> I solved.

How
